"""Update provider payment if from payment model

Revision ID: 094c362f322b
Revises: f3b4d395d0ab
Create Date: 2025-10-27 10:21:21.295313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '094c362f322b'
down_revision: str | None = 'f3b4d395d0ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'provider_payment_id', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'provider_payment_id', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
