"""Add datetime and inactive fields in movie model

Revision ID: 103c2ba0c2ba
Revises: e1757b51be8b
Create Date: 2025-10-06 14:25:35.911949

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '103c2ba0c2ba'
down_revision: str | None = 'e1757b51be8b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('inactive_at', sa.DateTime(), nullable=True))
    op.add_column('movie', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('movie', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'updated_at')
    op.drop_column('movie', 'created_at')
    op.drop_column('movie', 'inactive_at')
    # ### end Alembic commands ###
