"""Add datetime fields in payment model

Revision ID: 60d455b512c2
Revises: 094c362f322b
Create Date: 2025-10-28 19:26:32.974237

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '60d455b512c2'
down_revision: str | None = '094c362f322b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('payment', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'updated_at')
    op.drop_column('payment', 'created_at')
    # ### end Alembic commands ###
