"""Update Discount.expires_at data type

Revision ID: a3869ddfda8d
Revises: dd268fe984df
Create Date: 2025-10-21 07:32:36.637338

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3869ddfda8d'
down_revision: str | None = 'dd268fe984df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'discount', 'expires_at', existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'discount', 'expires_at', existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=True
    )
    # ### end Alembic commands ###
