"""Update Ticket model

Revision ID: a9d10f5882a9
Revises: be0ca7ba8e5d
Create Date: 2025-11-18 08:15:20.635731

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a9d10f5882a9'
down_revision: str | None = 'be0ca7ba8e5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ticket', ['barcode_value'])
    op.drop_column('ticket', 'ticket_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('ticket_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket', type_='unique')
    # ### end Alembic commands ###
