"""Add code as unique field in Invoice model

Revision ID: be0ca7ba8e5d
Revises: 60d455b512c2
Create Date: 2025-11-11 11:07:07.422231

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be0ca7ba8e5d'
down_revision: str | None = '60d455b512c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invoice', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice', type_='unique')
    # ### end Alembic commands ###
