"""Add datetime and inactive fields in showtime model

Revision ID: dd268fe984df
Revises: 103c2ba0c2ba
Create Date: 2025-10-13 09:31:27.275130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd268fe984df'
down_revision: str | None = '103c2ba0c2ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtime', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('showtime', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showtime', 'updated_at')
    op.drop_column('showtime', 'created_at')
    # ### end Alembic commands ###
