"""update auth_user and customer tables

Revision ID: e1757b51be8b
Revises: c00ec4af797d
Create Date: 2025-09-05 08:17:57.045486

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1757b51be8b'
down_revision: str | None = 'c00ec4af797d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'date_joined', existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.add_column('customer', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('customer', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('customer', sa.Column('birth_date', sa.Date(), nullable=False))
    op.drop_column('customer', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('customer', 'birth_date')
    op.drop_column('customer', 'updated_at')
    op.drop_column('customer', 'created_at')
    op.alter_column('auth_user', 'date_joined', existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###
