"""Add datetime fields in booking seat model

Revision ID: f3b4d395d0ab
Revises: a3869ddfda8d
Create Date: 2025-10-27 09:03:48.327984

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3b4d395d0ab'
down_revision: str | None = 'a3869ddfda8d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_seat', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('booking_seat', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_seat', 'updated_at')
    op.drop_column('booking_seat', 'created_at')
    # ### end Alembic commands ###
